In [1]:
class Vector(object):
    def __init__(self, coordinates):
        try:
            if not coordinates:
                raise ValueError
            self.coordinates = tuple(coordinates)
            self.dimension = len(coordinates)

        except ValueError:
            raise ValueError('The coordinates must be nonempty')

        except TypeError:
            raise TypeError('The coordinates must be an iterable')


    def __str__(self):
        return 'Vector: {}'.format(self.coordinates)


    def __eq__(self, v):
        return self.coordinates == v.coordinates

In [2]:
my_vector = Vector([1,2,3])

In [3]:
print(my_vector)

Vector: (1, 2, 3)


In [4]:
import numpy as np


In [7]:
x = np.array([8.218, -9.341])
y = np.array([-1.129, 2.111])
x + y

array([ 7.089, -7.23 ])

In [9]:
np.array([7.119, 8.215]) - np.array([-8.223, 0.878])

array([ 15.342,   7.337])

In [10]:
7.41 * np.array([1.671, -1.012, -0.318])

array([ 12.38211,  -7.49892,  -2.35638])