Linspace is a command to create arrays of certain sizes with certain ranges

In [2]:
import numpy as np

In [3]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
compare = 5
thresh = (x[:,:] <= compare)

In [4]:
thresh

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]], dtype=bool)

In [5]:
type(thresh)

numpy.ndarray

In [11]:
x = np.arange(3)


In [12]:
x.shape = (3,1)

In [14]:
x = np.array([[1],[2],[3]])

In [15]:
y = np.array([[4],[5],[6]])

In [20]:
y_int = (x - (y * 2))

In [22]:
y_int


array([[-7],
       [-8],
       [-9]])

In [12]:
xx = (y[1,:])

In [13]:
xx

array([ 7,  8,  9, 10, 11, 12, 13])

In [14]:
xx[::3]

array([ 7, 10, 13])

In [15]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
A[(1,2,3)]

IndexError: too many indices for array

In [16]:
A.shape

(4, 3)

In [17]:
x = np.arange(30).reshape(2,3,5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [18]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x[(1,2,3),]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [19]:
B.shape

NameError: name 'B' is not defined

In [20]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [21]:
x.shape

(2, 3, 1)

In [22]:
x[1,2]

array([6])

In [23]:
x[1:2]

array([[[4],
        [5],
        [6]]])

In [24]:
x[1:3,]

array([[[4],
        [5],
        [6]]])

In [25]:
x[(1,2,3),]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [26]:
a = np.arange(16).reshape(2,2,2,2)
print('a: ', a)

a:  [[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [27]:
a[...,0]

array([[[ 0,  2],
        [ 4,  6]],

       [[ 8, 10],
        [12, 14]]])

In [28]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

In [29]:
(a,b)

(array([1, 2, 3]), array([2, 3, 4]))

In [30]:
a = np.array([[1],[2],[3]])
print(a.shape)
b = np.array([[2],[3],[4]])
np.dstack((a,b))

(3, 1)


array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

In [55]:
x = np.array([[1,2,3],[4,5,6]])
def foo(arr):
    return arr.shape
#     return *arr.shape

foo(x) # (3,)

def bar(arr):
    a = (*arr.shape)
bar(x) #3



SyntaxError: can't use starred expression here (<ipython-input-55-161384122709>, line 9)

In [68]:
img = np.random.rand(540,960) * 255


In [75]:
print('x shape: ', x.shape)
line_img = np.zeros((*x.shape, 3), dtype=np.uint8)
#     line_img = np.zeros((*img.shape, 3), dtype=np.uint8)


x shape:  (540, 960, 3)


In [1]:
x = np.shape(3,1)


NameError: name 'np' is not defined